name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"


      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra


      - name: Make Directory for results
        run: |
          mkdir -p testResults
          cd testResults
          touch htmlreport.html


      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export /home/runner/work/API_tests/API_tests/testResults/htmlreport.html


      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults