name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2


      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"


      - name: Install newman
        run: |
          npm install -g newman
          npm install -g postman-reporting


      - name: Make Directory for results
        run: mkdir -p testResults


      - name: Run POSTMAN collection
        run: |
          par run petstore.collection.json --reporting testResults/htmlreport.html


      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults